name: sar2dem
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - asttokens=2.0.5
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - c-blosc2=2.12.0
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - comm=0.2.1
  - curl=8.1.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - imagecodecs=2023.1.23
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - kealib=1.5.0
  - krb5=1.19.4
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.3
  - libzip=1.8.0
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - postgresql=12.9
  - proj=6.2.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pygments=2.15.1
  - pytables=3.8.0
  - python=3.11.3
  - pyzmq=25.1.2
  - qhull=2020.2
  - readline=8.2
  - scikit-image=0.24.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tiledb=2.3.3
  - tk=8.6.12
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xz=5.4.2
  - zeromq=4.3.5
  - zfp=1.0.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - aenum==3.1.15
      - affine==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - appdirs==1.4.4
      - attrs==23.1.0
      - beautifulsoup4==4.12.3
      - cartopy==0.24.1
      - cdsapi==0.7.5
      - cffi==1.17.1
      - click==8.1.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorama==0.4.6
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==43.0.3
      - cycler==0.11.0
      - cytoolz==1.0.0
      - dataclasses-json==0.5.14
      - datapi==0.3.0
      - docker-pycreds==0.4.0
      - dominate==2.8.0
      - dustgoggles==0.7.5
      - filelock==3.14.0
      - fiona==1.9.4.post1
      - fonttools==4.40.0
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - geojson==3.0.1
      - geomet==1.0.0
      - geopandas==0.13.2
      - gitdb==4.0.10
      - gitpython==3.1.31
      - h5py==3.9.0
      - html2text==2020.1.16
      - huggingface-hub==0.15.1
      - imageio==2.31.1
      - imageio-ffmpeg==0.6.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - kaleido==0.2.1
      - kiwisolver==1.4.4
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - lightning-utilities==0.10.0
      - lmdb==1.4.1
      - lpips==0.1.4
      - lz4==4.3.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.20.1
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mmcv==2.2.0
      - mmengine==0.10.5
      - model-index==0.1.11
      - more-itertools==10.5.0
      - multidict==6.0.4
      - multiurl==0.3.3
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.2
      - pathtools==0.1.2
      - pdr==1.3.0
      - plotly==5.19.0
      - protobuf==4.23.3
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydar==1.4.0
      - pyparsing==3.1.0
      - pyproj==3.6.0
      - pyshp==2.3.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - rasterio==1.3.7
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rioxarray==0.14.1
      - rms-vax==1.0.4
      - safetensors==0.3.1
      - scikit-learn==1.5.0
      - scipy==1.11.1
      - seaborn==0.13.2
      - sentinelhub==3.9.1
      - sentinelsat==1.2.1
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - shapely==2.0.1
      - smmap==5.0.0
      - snuggs==1.4.7
      - soupsieve==2.5
      - tabulate==0.9.0
      - tbparse==0.0.9
      - tenacity==8.2.3
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.18
      - timm==0.9.2
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==1.0.0
      - torchmetrics==1.2.1
      - tqdm==4.65.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==1.26.20
      - utm==0.7.0
      - wandb==0.15.4
      - xarray==2023.5.0
      - yapf==0.43.0
      - yarl==1.9.4
